print("What is your name human?")
name = input()
print("How old are you (in years) ?")
age = int(input())
print("How tall are you (in meters) ?")
height = float(input())
print("How much do you weigh (in kilograms) ?")
weight = int(input())
print(name, " you are ", age, " and your BMI is ", weight/height)