# Display a box
print("##########")
print("#        #")
print("#        #")
print("##########")
print("  | |  *tock*")
print("  | |     *tock*")
print("  | <-*)")
print("  | |(()")
print("  | |\"/")
print("  | |'")