print("##########")
print("#        #")
print("#  ____  #")
print("##########")
print()
print("Enter a character for an eye:")
eye = input()
print("##########")
print("# "+eye+"    "+  eye+" #")
print("#  ____  #")
print("##########")